//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_01_HocSinh.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HocSinhRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HocSinhRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EF_01_HocSinh.Resources.HocSinhRes", typeof(HocSinhRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap hoc sinh ID la so!.
        /// </summary>
        internal static string ErrorHocSinhId {
            get {
                return ResourceManager.GetString("ErrorHocSinhId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap ho va ten tu 2 den 20 ky tu!.
        /// </summary>
        internal static string ErrorHoVaTen {
            get {
                return ResourceManager.GetString("ErrorHoVaTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap lop ID la so!.
        /// </summary>
        internal static string ErrorLopId {
            get {
                return ResourceManager.GetString("ErrorLopId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap nam trong khoang tu nam 2001 den 2013!.
        /// </summary>
        internal static string ErrorNam {
            get {
                return ResourceManager.GetString("ErrorNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap dung dinh dang (yyyy/MM/dd)!.
        /// </summary>
        internal static string ErrorNgaySinh {
            get {
                return ResourceManager.GetString("ErrorNgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap que quan co chua it nhat 1 thanh pho!.
        /// </summary>
        internal static string ErrorQueQuan {
            get {
                return ResourceManager.GetString("ErrorQueQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap si so la so!.
        /// </summary>
        internal static string ErrorSiSo {
            get {
                return ResourceManager.GetString("ErrorSiSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho ten phai co 2 tu tro len!.
        /// </summary>
        internal static string ErrorSoTu {
            get {
                return ResourceManager.GetString("ErrorSoTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap ten lop khong duoc qua 10 ky tu!.
        /// </summary>
        internal static string ErrorTenLop {
            get {
                return ResourceManager.GetString("ErrorTenLop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap gia tri tu khoang 0 den 20!.
        /// </summary>
        internal static string ErrorValue {
            get {
                return ResourceManager.GetString("ErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap hoc sinh ID: .
        /// </summary>
        internal static string HocSinhId {
            get {
                return ResourceManager.GetString("HocSinhId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ho va ten: .
        /// </summary>
        internal static string HoVaTen {
            get {
                return ResourceManager.GetString("HoVaTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sach trong!.
        /// </summary>
        internal static string LogDanhSachTrong {
            get {
                return ResourceManager.GetString("LogDanhSachTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoc sinh dang o trong lop!.
        /// </summary>
        internal static string LogHocSinhDangOTrongLop {
            get {
                return ResourceManager.GetString("LogHocSinhDangOTrongLop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong tim thay hoc sinh!.
        /// </summary>
        internal static string LogKhongTimThayHocSinh {
            get {
                return ResourceManager.GetString("LogKhongTimThayHocSinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong tim thay lop!.
        /// </summary>
        internal static string LogKhongTimThayLop {
            get {
                return ResourceManager.GetString("LogKhongTimThayLop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong tim thay lop cu!.
        /// </summary>
        internal static string LogKhongTimThayLopCu {
            get {
                return ResourceManager.GetString("LogKhongTimThayLopCu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong tim thay lop moi!.
        /// </summary>
        internal static string LogKhongTimThayLopMoi {
            get {
                return ResourceManager.GetString("LogKhongTimThayLopMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lop du si so!.
        /// </summary>
        internal static string LogLopDuSiSo {
            get {
                return ResourceManager.GetString("LogLopDuSiSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh cong!.
        /// </summary>
        internal static string LogThanhCong {
            get {
                return ResourceManager.GetString("LogThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap lop ID: .
        /// </summary>
        internal static string LopId {
            get {
                return ResourceManager.GetString("LopId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ngay sinh (nam/thang/ngay): .
        /// </summary>
        internal static string NgaySinh {
            get {
                return ResourceManager.GetString("NgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap que quan: .
        /// </summary>
        internal static string QueQuan {
            get {
                return ResourceManager.GetString("QueQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap si so: .
        /// </summary>
        internal static string SiSo {
            get {
                return ResourceManager.GetString("SiSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten lop: .
        /// </summary>
        internal static string TenLop {
            get {
                return ResourceManager.GetString("TenLop", resourceCulture);
            }
        }
    }
}
